name: MacOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.9
      PYTHON_VERSION: python3.7
      PYTHON_DOWNLOAD_URL: https://www.python.org/ftp/python/3.7.7/python-3.7.7-macosx10.9.pkg

    steps:
    - uses: actions/checkout@v2
    
    # Download and install Python instead of using the setup_python
    # as the python in OSX was compiled in 10.14, which means that the wheels
    # are incompatible with older MacOS versions
    - name: Download and install Python
      run: |
        curl $PYTHON_DOWNLOAD_URL --output python_installer.pkg
        sudo installer -pkg python_installer.pkg -target /

    - name: Checkout submodules
      run: | 
        git submodule init
        git submodule update

    - name: Build zlib
      run: |
         git clone https://github.com/madler/zlib.git
         mkdir zlib-build
         cd zlib-build
         cmake ../zlib -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../zlib-install
         make install
         cd ..

    - name: Build ITK
      run: |
        mkdir ITK-build
        cd ITK-build
        cmake \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_TESTING=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=../ITK-install \
            ../ITK
        make install
        cd ..

    - name: Build charm-gems
      run: |
        $PYTHON_VERSION -m pip install --user --upgrade setuptools wheel
        $PYTHON_VERSION setup.py bdist_wheel
      env:
        ITK_DIR: ITK-install
        ZLIB_INCLUDE_DIR: zlib-install/lib
        ZLIB_LIBRARY: zlib-install/lib/libz.a

    - name: Test install and import
      run: |
        python -m pip install charm-gems -f dist/
        python -c 'import charm_gems'

    - name: Upload artifact
      uses: kittaakos/upload-artifact-as-is@v0
      with:
        path: dist/*.whl
