name: MacOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Checkout submodules
      run: | 
        git submodule init
        git submodule update

    - name: Build zlib
      run: |
         export MACOSX_DEPLOYMENT_TARGET=10.9
         git clone https://github.com/madler/zlib.git
         mkdir zlib-build
         cd zlib-build
         cmake ../zlib -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../zlib-install
         make install
         cd ..

    - name: Build ITK
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.9
        mkdir ITK-build
        cd ITK-build
        cmake \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_TESTING=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=../ITK-install \
            ../ITK
        make install
        cd ..

    - name: Build charm-gems
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.9
        python -m pip install --user --upgrade setuptools wheel
        ITK_DIR=ITK-install ZLIB_INCLUDE_DIR=zlib-install/lib ZLIB_LIBRARY=zlib-install/lib/libz.a python setup.py bdist_wheel
        
    - name: Test install and import
      run: |
        python -m pip install charm-gems -f dist/
        python -c 'import charm_gems'

    - name: Upload artifact
      uses: kittaakos/upload-artifact-as-is@v0
      with:
        path: dist/*.whl
