name: MacOS Build

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.9
      PYTHON_VERSION: python3.7
      PYTHON_DOWNLOAD_URL: https://www.python.org/ftp/python/3.7.7/python-3.7.7-macosx10.9.pkg

    steps:
    - uses: actions/checkout@v2
    
    # Download and install Python instead of using the setup_python
    # as the python in OSX was compiled in 10.14, which means that the wheels
    # are incompatible with older MacOS versions
    - name: Download and install Python
      run: |
        curl \
          https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.9.pkg \
          --output python_installer.pkg
        sudo installer -pkg python_installer.pkg -target /

        curl \
          https://www.python.org/ftp/python/3.7.7/python-3.7.7-macosx10.9.pkg \
          --output python_installer.pkg
        sudo installer -pkg python_installer.pkg -target /

        curl \
          https://www.python.org/ftp/python/3.8.3/python-3.8.3-macosx10.9.pkg \
          --output python_installer.pkg
        sudo installer -pkg python_installer.pkg -target /


    - name: Checkout submodules
      run: | 
        git submodule init
        git submodule update

    - name: Build zlib
      run: |
         git clone https://github.com/madler/zlib.git
         mkdir zlib-build
         cd zlib-build
         cmake ../zlib -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../zlib-install
         make install
         cd ..

    - name: Build ITK
      run: |
        mkdir ITK-build
        cd ITK-build
        cmake \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_TESTING=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=../ITK-install \
            ../ITK
        make install
        cd ..

    - name: Build charm-gems
      run: |
        .github/workflows/macos_build.sh python3.6
        .github/workflows/macos_build.sh python3.7
        .github/workflows/macos_build.sh python3.8
      env:
        ITK_DIR: ITK-install
        ZLIB_INCLUDE_DIR: zlib-install/lib
        ZLIB_LIBRARY: zlib-install/lib/libz.a

    - name: Upload artifact
      uses: kittaakos/upload-artifact-as-is@v0
      with:
        path: dist/*.whl

    - name: Upload to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
