name: MacOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: | 
        git submodule init
        git submodule update
    - name: Build ITK
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.9
        mkdir ITK-build
        cd ITK-build
        cmake \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_TESTING=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DCMAKE_INSTALL_PREFIX=../ITK-install \
            ../ITK
        make install
        cd ..
    - name: Install charm-gems
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.9
        ITK_DIR=ITK-install python3.7 setup.py install
