name: Windows Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: | 
        git submodule init
        git submodule update
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Build zlib
      run: |
         git clone https://github.com/madler/zlib.git
         md zlib-build
         cd zlib-build
         cmake ..\zlib -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="..\zlib-install"
         cmake --build . --config Release --target install
         cd ..
         dir
  
    - name: Build ITK
      run: |
        md ITK-build
        cd ITK-build
        cmake.exe -G "Visual Studio 16 2019" -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF ..\ITK
        msbuild INSTALL.vcxproj
        cd ..
      shell: cmd
         
    - name: Build charm-gems wheel
      run: |
        python -m pip install --user --upgrade setuptools wheel
        python setup.py bdist_wheel
      env:
        ZLIB_INCLUDE_DIR: .\zlib-install\include
        ZLIB_LIBRARY: .\zlib-install\lib\zlibstatic.lib

    - name: Test install and import
      run: |
        python -m pip install charm-gems -f .\dist\
        python -c 'import charm_gems'

    - name: Upload artifact
      uses: kittaakos/upload-artifact-as-is@v0
      with:
        path: .\dist\*.whl
