name: Windows Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: | 
        git submodule init
        git submodule update
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Build zlib
      run: |
         git clone https://github.com/madler/zlib.git
         md zlib-build
         cd zlib-build
         cmake ..\zlib -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="..\zlib-install"
         cmake --build . --config Release --target install
         cd ..
         dir
  
    - name: Build ITK
      run: |
        md ITK-build
        cd ITK-build
        cmake.exe -G "Visual Studio 16 2019" -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Release ..\ITK
        cmake --build . --config Release --target Install
        cd ..
      shell: cmd
         

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'
    - run: .github\workflows\windows_build.bat

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: .github\workflows\windows_build.bat

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - run: .github\workflows\windows_build.bat


    - name: Upload artifact
      uses: kittaakos/upload-artifact-as-is@v0
      with:
        path: .\dist\*.whl


    - name: Upload to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
